# Generated by Django 4.1.1 on 2022-09-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxibooking', '0002_cars_delete_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phoneNumber', models.CharField(blank=True, max_length=255)),
                ('createdAT', models.DateTimeField(auto_now_add=True)),
                ('BookedCarID', models.CharField(blank=True, max_length=255)),
                ('carbrand', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Taxibooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromAddress', models.CharField(blank=True, max_length=255)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('BookedDate', models.CharField(blank=True, max_length=255)),
                ('BookedTime', models.CharField(blank=True, max_length=255)),
                ('carId', models.CharField(blank=True, max_length=255)),
                ('custmerid', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='cartype',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
