# Generated by Django 4.1.1 on 2022-09-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxibooking', '0005_cars_geartype_cars_milage_cars_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxibooking',
            name='toAddress',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
