# Generated by Django 4.1.1 on 2022-09-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxibooking', '0006_taxibooking_toaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinformation',
            old_name='BookedCarID',
            new_name='bookedCarID',
        ),
        migrations.RenameField(
            model_name='customerinformation',
            old_name='carbrand',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='taxibooking',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='taxibooking',
            old_name='fromAddress',
            new_name='fromAdress',
        ),
        migrations.RenameField(
            model_name='taxibooking',
            old_name='toAddress',
            new_name='hereturn',
        ),
        migrations.RemoveField(
            model_name='customerinformation',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='taxibooking',
            name='time',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='taxibooking',
            name='toAdress',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
